trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: DevSecops_Agent

stages:
# =========================
# Stage 1: Init + Scan
# =========================
- stage: Terraform_Installation_Init
  displayName: "Terraform Init, TFLint, TFsec"
  jobs:
    - job: TerraformInstallation
      displayName: Terraform Installation & Scan
      steps:

      - task: TerraformInstaller@1
        displayName: Terraform Installation
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Enviroment/dev'
          backendServiceArm: 'Federation Based'
          backendAzureRmResourceGroupName: 'Vaishno-RG'
          backendAzureRmStorageAccountName: 'vaishnostg1'
          backendAzureRmContainerName: 'vaishnocontainer1'
          backendAzureRmKey: 'Dev.terraform.tfstate'

      # -------- TFLint --------
      - script: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version
        displayName: Install TFLint

      - script: |
          cd $(System.DefaultWorkingDirectory)/Enviroment/dev
          tflint --init
          tflint
        displayName: Run TFLint

      # -------- TFsec --------
      - script: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version
        displayName: Install TFsec

      - script: |
          tfsec $(System.DefaultWorkingDirectory)/Enviroment/dev
        displayName: Run TFsec Security Scan

      - task: PublishPipelineArtifact@1
        displayName: Publish Terraform Files
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/Enviroment/dev'
          artifact: 'Terraform_config'

# =========================
# Stage 2: Terraform Plan
# =========================
- stage: Terraform_Plan
  displayName: "Terraform Plan"
  dependsOn: Terraform_Installation_Init
  condition: succeeded('Terraform_Installation_Init')
  jobs:
    - job: Terraform_Plan
      displayName: Terraform Plan
      steps:

      - task: DownloadPipelineArtifact@2
        displayName: Download Terraform Files
        inputs:
          artifact: 'Terraform_config'
          targetPath: '$(System.DefaultWorkingDirectory)/Enviroment/dev'

      - task: TerraformTask@5
        displayName: Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Enviroment/dev'
          environmentServiceNameAzureRM: 'Federation Based'

# =========================
# Stage 3: Terraform Apply
# =========================
- stage: Terraform_Apply
  displayName: "Terraform Apply"
  dependsOn: Terraform_Plan
  condition: succeeded('Terraform_Plan')
  jobs:
    - job: Terraform_Apply
      displayName: Terraform Apply
      steps:

      - task: DownloadPipelineArtifact@2
        displayName: Download Terraform Files
        inputs:
          artifact: 'Terraform_config'
          targetPath: '$(System.DefaultWorkingDirectory)/Enviroment/dev'

      - task: TerraformTask@5
        displayName: Terraform Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Enviroment/dev'
          commandOptions: '--auto-approve'
          environmentServiceNameAzureRM: 'Federation Based'
